/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package movie_world;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author DELL
 */
public class Actor_pannel extends javax.swing.JPanel {

    /**
     * Creates new form Actor_pannel
     */
   int actorNO =0;
   JSONArray js = new JSONArray();
    
    public Actor_pannel(int actorno,JSONArray actoArray) {
        actorNO = actorno;
        js = actoArray;
        initComponents();
        favoriteaddBt.setVisible(false);
        delfavoritebt.setVisible(false);
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        professionLb = new javax.swing.JLabel();
        popularity_progress = new javax.swing.JProgressBar();
        moviesBt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        favoriteaddBt = new javax.swing.JButton();
        delfavoritebt = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        setOpaque(false);
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 196, 25));
        jLabel1.setText("NAME");
        add(jLabel1);
        jLabel1.setBounds(21, 36, 60, 15);

        nameLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLb.setForeground(new java.awt.Color(252, 196, 25));
        nameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLb.setText("Actor Name");
        add(nameLb);
        nameLb.setBounds(140, 40, 160, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 196, 25));
        jLabel3.setText("PROFESSION");
        add(jLabel3);
        jLabel3.setBounds(20, 90, 90, 15);

        professionLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        professionLb.setForeground(new java.awt.Color(252, 196, 25));
        professionLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        professionLb.setText("Acting");
        add(professionLb);
        professionLb.setBounds(140, 90, 140, 15);

        popularity_progress.setBackground(new java.awt.Color(0, 0, 0));
        popularity_progress.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        popularity_progress.setForeground(new java.awt.Color(252, 196, 25));
        popularity_progress.setMaximum(10);
        popularity_progress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        popularity_progress.setStringPainted(true);
        add(popularity_progress);
        popularity_progress.setBounds(20, 230, 240, 20);

        moviesBt.setBackground(new java.awt.Color(0, 0, 0));
        moviesBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-next-page-30.png"))); // NOI18N
        moviesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesBtActionPerformed(evt);
            }
        });
        add(moviesBt);
        moviesBt.setBounds(180, 130, 60, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 196, 25));
        jLabel5.setText("POPULAR MOVIES");
        add(jLabel5);
        jLabel5.setBounds(20, 140, 110, 15);

        favoriteaddBt.setBackground(new java.awt.Color(0, 0, 0));
        favoriteaddBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hearts-20 (1).png"))); // NOI18N
        favoriteaddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteaddBtActionPerformed(evt);
            }
        });
        add(favoriteaddBt);
        favoriteaddBt.setBounds(240, 10, 50, 30);

        delfavoritebt.setBackground(new java.awt.Color(0, 0, 0));
        delfavoritebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hearts-20.png"))); // NOI18N
        add(delfavoritebt);
        delfavoritebt.setBounds(240, 10, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void moviesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesBtActionPerformed

    }//GEN-LAST:event_moviesBtActionPerformed

    private void favoriteaddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteaddBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favoriteaddBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delfavoritebt;
    public javax.swing.JButton favoriteaddBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JButton moviesBt;
    public javax.swing.JLabel nameLb;
    public javax.swing.JProgressBar popularity_progress;
    public javax.swing.JLabel professionLb;
    // End of variables declaration//GEN-END:variables
}
